/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.gzcg.bd;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-07-09 08:15:27
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class samplevo extends SuperVO {
	private java.lang.String pk_sample;
	private java.lang.String pk_corp;
	private java.lang.String vqctype;
	private java.lang.String vsampleno;
	private java.lang.String vsamplenofar;
	private java.lang.String pk_invmandoc;
	private java.lang.String vorderbill;
	private java.lang.String vstockbatch;
	private nc.vo.pub.lang.UFBoolean burgent;
	private nc.vo.pub.lang.UFDate ddate;
	private java.lang.String pk_user;
	private java.lang.String vmemo;
	private java.lang.String vdef1;
	private java.lang.String vdef2;
	private java.lang.String vdef3;
	private java.lang.String vdef4;
	private java.lang.String vdef5;
	private java.lang.String vdef6;
	private java.lang.String vdef7;
	private java.lang.String vdef8;
	private java.lang.String vdef9;
	private java.lang.String vdef10;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_SAMPLE = "pk_sample";
	public static final String PK_CORP = "pk_corp";
	public static final String VQCTYPE = "vqctype";
	public static final String VSAMPLENO = "vsampleno";
	public static final String VSAMPLENOFAR = "vsamplenofar";
	public static final String PK_INVMANDOC = "pk_invmandoc";
	public static final String VORDERBILL = "vorderbill";
	public static final String VSTOCKBATCH = "vstockbatch";
	public static final String BURGENT = "burgent";
	public static final String DDATE = "ddate";
	public static final String PK_USER = "pk_user";
	public static final String VMEMO = "vmemo";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF5 = "vdef5";
	public static final String VDEF6 = "vdef6";
	public static final String VDEF7 = "vdef7";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF9 = "vdef9";
	public static final String VDEF10 = "vdef10";
			
	/**
	 * 属性pk_sample的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sample () {
		return pk_sample;
	}   
	/**
	 * 属性pk_sample的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newPk_sample java.lang.String
	 */
	public void setPk_sample (java.lang.String newPk_sample ) {
	 	this.pk_sample = newPk_sample;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newPk_corp java.lang.String
	 */
	public void setPk_corp (java.lang.String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性vqctype的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVqctype () {
		return vqctype;
	}   
	/**
	 * 属性vqctype的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVqctype java.lang.String
	 */
	public void setVqctype (java.lang.String newVqctype ) {
	 	this.vqctype = newVqctype;
	} 	  
	/**
	 * 属性vsampleno的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVsampleno () {
		return vsampleno;
	}   
	/**
	 * 属性vsampleno的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVsampleno java.lang.String
	 */
	public void setVsampleno (java.lang.String newVsampleno ) {
	 	this.vsampleno = newVsampleno;
	} 	  
	/**
	 * 属性vsamplenofar的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVsamplenofar () {
		return vsamplenofar;
	}   
	/**
	 * 属性vsamplenofar的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVsamplenofar java.lang.String
	 */
	public void setVsamplenofar (java.lang.String newVsamplenofar ) {
	 	this.vsamplenofar = newVsamplenofar;
	} 	  
	/**
	 * 属性pk_invmandoc的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getPk_invmandoc () {
		return pk_invmandoc;
	}   
	/**
	 * 属性pk_invmandoc的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newPk_invmandoc java.lang.String
	 */
	public void setPk_invmandoc (java.lang.String newPk_invmandoc ) {
	 	this.pk_invmandoc = newPk_invmandoc;
	} 	  
	/**
	 * 属性vorderbill的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVorderbill () {
		return vorderbill;
	}   
	/**
	 * 属性vorderbill的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVorderbill java.lang.String
	 */
	public void setVorderbill (java.lang.String newVorderbill ) {
	 	this.vorderbill = newVorderbill;
	} 	  
	/**
	 * 属性vstockbatch的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVstockbatch () {
		return vstockbatch;
	}   
	/**
	 * 属性vstockbatch的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVstockbatch java.lang.String
	 */
	public void setVstockbatch (java.lang.String newVstockbatch ) {
	 	this.vstockbatch = newVstockbatch;
	} 	  
	/**
	 * 属性burgent的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBurgent () {
		return burgent;
	}   
	/**
	 * 属性burgent的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newBurgent nc.vo.pub.lang.UFBoolean
	 */
	public void setBurgent (nc.vo.pub.lang.UFBoolean newBurgent ) {
	 	this.burgent = newBurgent;
	} 	  
	/**
	 * 属性ddate的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDdate () {
		return ddate;
	}   
	/**
	 * 属性ddate的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newDdate nc.vo.pub.lang.UFDate
	 */
	public void setDdate (nc.vo.pub.lang.UFDate newDdate ) {
	 	this.ddate = newDdate;
	} 	  
	/**
	 * 属性pk_user的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getPk_user () {
		return pk_user;
	}   
	/**
	 * 属性pk_user的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newPk_user java.lang.String
	 */
	public void setPk_user (java.lang.String newPk_user ) {
	 	this.pk_user = newPk_user;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVmemo java.lang.String
	 */
	public void setVmemo (java.lang.String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef1 java.lang.String
	 */
	public void setVdef1 (java.lang.String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef2 java.lang.String
	 */
	public void setVdef2 (java.lang.String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef3 java.lang.String
	 */
	public void setVdef3 (java.lang.String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef4 java.lang.String
	 */
	public void setVdef4 (java.lang.String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef5 java.lang.String
	 */
	public void setVdef5 (java.lang.String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef6 java.lang.String
	 */
	public void setVdef6 (java.lang.String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef7 java.lang.String
	 */
	public void setVdef7 (java.lang.String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef8 java.lang.String
	 */
	public void setVdef8 (java.lang.String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef9 java.lang.String
	 */
	public void setVdef9 (java.lang.String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newVdef10 java.lang.String
	 */
	public void setVdef10 (java.lang.String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-07-09 08:15:27
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-07-09 08:15:27
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-07-09 08:15:27
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_sample";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-07-09 08:15:27
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gzcg_bd_sampledoc";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-07-09 08:15:27
	  */
     public samplevo() {
		super();	
	}    
} 
