/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product.                              *
 \***************************************************************/

package nc.bs.sc.order;


import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;

import javax.naming.NamingException;

import nc.bs.framework.common.NCLocator;
import nc.bs.pub.DataManageObject;
import nc.itf.sc.order.ISCForCGOrderService;
import nc.itf.uap.IUAPQueryBS;
import nc.jdbc.framework.processor.BeanListProcessor;
import nc.vo.pub.BusinessException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDouble;
import nc.vo.sc.order.OrderDdlbVO;
import nc.vo.sc.order.OrderHeaderVO;
import nc.vo.sc.order.OrderItemVO;
import nc.vo.sc.order.OrderVO;
import nc.vo.sc.pub.ScConstants;


/**
 * Order的DMO类。
 *
 * 创建日期：(2001-6-23)
 * @author：
 */
public class OrderDMOForCG  extends DataManageObject implements ISCForCGOrderService {

	 public OrderDMOForCG() throws NamingException {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	     * 材料出库参照订单
	     * gc
	     * @exception java.sql.SQLException 异常说明。
	     */
	    public OrderHeaderVO[] queryRefHead(String condition) throws SQLException {
	    	String sql = "select  corderid, vordercode, pk_corp, cpurorganization, cwareid, dorderdate, cvendorid, caccountbankid, cdeptid, cemployeeid, cbiztype, creciever, cgiveinvoicevendor, ctransmodeid, ctermProtocolid, ibillstatus, vmemo, caccountyear, coperator, vdef1, vdef2, vdef3, vdef4, vdef5, vdef6, vdef7, vdef8, vdef9, vdef10, vdef11, vdef12, vdef13, vdef14, vdef15, vdef16, vdef17, vdef18, vdef19, vdef20, pk_defdoc1, pk_defdoc2, pk_defdoc3, pk_defdoc4, pk_defdoc5, pk_defdoc6, pk_defdoc7, pk_defdoc8, pk_defdoc9, pk_defdoc10, pk_defdoc11, pk_defdoc12, pk_defdoc13, pk_defdoc14, pk_defdoc15, pk_defdoc16, pk_defdoc17, pk_defdoc18, pk_defdoc19, pk_defdoc20, ts, iprintcount, tmaketime, taudittime, tlastmaketime  from sc_order where isnull(sc_order.dr,0)=0 " + condition;
	        OrderHeaderVO orders[] = null;
	        Vector v = new Vector();
	        Connection con = null;
	        PreparedStatement stmt = null;
	        try {
	        	 con = getConnection();
	             stmt = con.prepareStatement(sql);
	             ResultSet rs = stmt.executeQuery();
	            //
	            while (rs.next()) {
	                OrderHeaderVO order = new OrderHeaderVO();
	                // corderid :
	                String corderid = rs.getString(1);
	                order.setCorderid(corderid == null ? null : corderid.trim());
	                // vordercode :
	                String vordercode = rs.getString(2);
	                order.setVordercode(vordercode == null ? null : vordercode.trim());
	                // pk_corp :
	                String pk_corp = rs.getString(3);
	                order.setPk_corp(pk_corp == null ? null : pk_corp.trim());
	                // cpurorganization :
	                String cpurorganization = rs.getString(4);
	                order.setCpurorganization(cpurorganization == null ? null : cpurorganization.trim());
	                // cwareid :
	                String cwareid = rs.getString(5);
	                order.setCwareid(cwareid == null ? null : cwareid.trim());
	                // dorderdate :
	                String dorderdate = rs.getString(6);
	                order.setDorderdate(dorderdate == null ? null : new UFDate(dorderdate.trim(), false));
	                // cvendorid :
	                String cvendorid = rs.getString(7);
	                order.setCvendorid(cvendorid == null ? null : cvendorid.trim());
	                // caccountbankid :
	                String caccountbankid = rs.getString(8);
	                order.setCaccountbankid(caccountbankid == null ? null : caccountbankid.trim());
	                // cdeptid :
	                String cdeptid = rs.getString(9);
	                order.setCdeptid(cdeptid == null ? null : cdeptid.trim());
	                // cemployeeid :
	                String cemployeeid = rs.getString(10);
	                order.setCemployeeid(cemployeeid == null ? null : cemployeeid.trim());
	                // cbiztypeid :
	                String cbiztypeid = rs.getString(11);
	                order.setCbiztype(cbiztypeid == null ? null : cbiztypeid.trim());
	                // creciever :
	                String creciever = rs.getString(12);
	                order.setCreciever(creciever == null ? null : creciever.trim());
	                // cgiveinvoicevendor :
	                String cgiveinvoicevendor = rs.getString(13);
	                order.setCgiveinvoicevendor(cgiveinvoicevendor == null ? null : cgiveinvoicevendor.trim());
	                // ctransmodeid :
	                String ctransmodeid = rs.getString(14);
	                order.setCtransmodeid(ctransmodeid == null ? null : ctransmodeid.trim());
	                // ctermProtocolid :
	                String ctermProtocolid = rs.getString(15);
	                order.setCtermProtocolid(ctermProtocolid == null ? null : ctermProtocolid.trim());
	                // ibillstatus :
	                Integer ibillstatus = (Integer) rs.getObject(16);
	                order.setIbillstatus(ibillstatus == null ? null : ibillstatus);
	                // vmemo :
	                String vmemo = rs.getString(17);
	                order.setVmemo(vmemo == null ? null : vmemo.trim());
	                // caccountyear :
	                String caccountyear = rs.getString(18);
	                order.setCaccountyear(caccountyear == null ? null : caccountyear.trim());
	                // coperator :
	                String coperator = rs.getString(19);
	                order.setCoperator(coperator == null ? null : coperator.trim());
	                // vdef1 :
	                String vdef1 = rs.getString(20);
	                order.setVdef1(vdef1 == null ? null : vdef1.trim());
	                // vdef2 :
	                String vdef2 = rs.getString(21);
	                order.setVdef2(vdef2 == null ? null : vdef2.trim());
	                // vdef3 :
	                String vdef3 = rs.getString(22);
	                order.setVdef3(vdef3 == null ? null : vdef3.trim());
	                // vdef4 :
	                String vdef4 = rs.getString(23);
	                order.setVdef4(vdef4 == null ? null : vdef4.trim());
	                // vdef5 :
	                String vdef5 = rs.getString(24);
	                order.setVdef5(vdef5 == null ? null : vdef5.trim());
	                // vdef6 :
	                String vdef6 = rs.getString(25);
	                order.setVdef6(vdef6 == null ? null : vdef6.trim());
	                // vdef7 :
	                String vdef7 = rs.getString(26);
	                order.setVdef7(vdef7 == null ? null : vdef7.trim());
	                // vdef8 :
	                String vdef8 = rs.getString(27);
	                order.setVdef8(vdef8 == null ? null : vdef8.trim());
	                // vdef9 :
	                String vdef9 = rs.getString(28);
	                order.setVdef9(vdef9 == null ? null : vdef9.trim());
	                // vdef10 :
	                String vdef10 = rs.getString(29);
	                order.setVdef10(vdef10 == null ? null : vdef10.trim());
	                //
	                //
	                String vdef11 = rs.getString(30);
	                order.setVdef11(vdef11 == null ? null : vdef11.trim());
	                //
	                String vdef12 = rs.getString(31);
	                order.setVdef12(vdef12 == null ? null : vdef12.trim());
	                //
	                String vdef13 = rs.getString(32);
	                order.setVdef13(vdef13 == null ? null : vdef13.trim());
	                //
	                String vdef14 = rs.getString(33);
	                order.setVdef14(vdef14 == null ? null : vdef14.trim());
	                //
	                String vdef15 = rs.getString(34);
	                order.setVdef15(vdef15 == null ? null : vdef15.trim());
	                //
	                String vdef16 = rs.getString(35);
	                order.setVdef16(vdef16 == null ? null : vdef16.trim());
	                //
	                String vdef17 = rs.getString(36);
	                order.setVdef17(vdef17 == null ? null : vdef17.trim());
	                //
	                String vdef18 = rs.getString(37);
	                order.setVdef18(vdef18 == null ? null : vdef18.trim());
	                //
	                String vdef19 = rs.getString(38);
	                order.setVdef19(vdef19 == null ? null : vdef19.trim());
	                //
	                String vdef20 = rs.getString(39);
	                order.setVdef20(vdef20 == null ? null : vdef20.trim());
	                //
	                String pk_defdoc1 = rs.getString(40);
	                order.setPKDefDoc1(pk_defdoc1 == null ? null : pk_defdoc1.trim());
	                //
	                String pk_defdoc2 = rs.getString(41);
	                order.setPKDefDoc2(pk_defdoc2 == null ? null : pk_defdoc2.trim());
	                //
	                String pk_defdoc3 = rs.getString(42);
	                order.setPKDefDoc3(pk_defdoc3 == null ? null : pk_defdoc3.trim());
	                //
	                String pk_defdoc4 = rs.getString(43);
	                order.setPKDefDoc4(pk_defdoc4 == null ? null : pk_defdoc4.trim());
	                //
	                String pk_defdoc5 = rs.getString(44);
	                order.setPKDefDoc5(pk_defdoc5 == null ? null : pk_defdoc5.trim());
	                //
	                String pk_defdoc6 = rs.getString(45);
	                order.setPKDefDoc6(pk_defdoc6 == null ? null : pk_defdoc6.trim());
	                //
	                String pk_defdoc7 = rs.getString(46);
	                order.setPKDefDoc7(pk_defdoc7 == null ? null : pk_defdoc7.trim());
	                //
	                String pk_defdoc8 = rs.getString(47);
	                order.setPKDefDoc8(pk_defdoc8 == null ? null : pk_defdoc8.trim());
	                //
	                String pk_defdoc9 = rs.getString(48);
	                order.setPKDefDoc9(pk_defdoc9 == null ? null : pk_defdoc9.trim());
	                //
	                String pk_defdoc10 = rs.getString(49);
	                order.setPKDefDoc10(pk_defdoc10 == null ? null : pk_defdoc10.trim());
	                //
	                String pk_defdoc11 = rs.getString(50);
	                order.setPKDefDoc11(pk_defdoc11 == null ? null : pk_defdoc11.trim());
	                //
	                String pk_defdoc12 = rs.getString(51);
	                order.setPKDefDoc12(pk_defdoc12 == null ? null : pk_defdoc12.trim());
	                //
	                String pk_defdoc13 = rs.getString(52);
	                order.setPKDefDoc13(pk_defdoc13 == null ? null : pk_defdoc13.trim());
	                //
	                String pk_defdoc14 = rs.getString(53);
	                order.setPKDefDoc14(pk_defdoc14 == null ? null : pk_defdoc14.trim());
	                //
	                String pk_defdoc15 = rs.getString(54);
	                order.setPKDefDoc15(pk_defdoc15 == null ? null : pk_defdoc15.trim());
	                //
	                String pk_defdoc16 = rs.getString(55);
	                order.setPKDefDoc16(pk_defdoc16 == null ? null : pk_defdoc16.trim());
	                //
	                String pk_defdoc17 = rs.getString(56);
	                order.setPKDefDoc17(pk_defdoc17 == null ? null : pk_defdoc17.trim());
	                //
	                String pk_defdoc18 = rs.getString(57);
	                order.setPKDefDoc18(pk_defdoc18 == null ? null : pk_defdoc18.trim());
	                //
	                String pk_defdoc19 = rs.getString(58);
	                order.setPKDefDoc19(pk_defdoc19 == null ? null : pk_defdoc19.trim());
	                //
	                String pk_defdoc20 = rs.getString(59);
	                order.setPKDefDoc20(pk_defdoc20 == null ? null : pk_defdoc20.trim());
	                // ts :
	                String ts = rs.getString(60);
	                order.setTs(ts == null ? null : ts.trim());
	                // iprintcount :
	                Integer iprintcount = (Integer) rs.getObject(61);
	                order.setIprintcount(iprintcount == null ? null : iprintcount);

	                String tmaketime = rs.getString(62);
	                order.setTmaketime(tmaketime == null ? null : tmaketime.trim());
	                String taudittime = rs.getString(63);
	                order.setTaudittime(taudittime == null ? null : taudittime.trim());
	                String tlastmaketime = rs.getString(64);
	                order.setTlastmaketime(tlastmaketime == null ? null : tlastmaketime.trim());

	                v.addElement(order);
	            }
	        } finally {
	            try {
	                if (stmt != null) {
	                    stmt.close();
	                }
	            } catch (Exception e) {
	            }
	            try {
	                if (con != null) {
	                    con.close();
	                }
	            } catch (Exception e) {
	            }
	        }
	        orders = new OrderHeaderVO[v.size()];
	        if (v.size() > 0) {
	            v.copyInto(orders);
	        }

	        /*************************************************************/
	        // 保留的系统管理接口：
	        afterCallMethod("nc.bs.sc.order.OrderDMO", "queryAllHead", new Object[] {condition });
	        /*************************************************************/

	        return orders;
	    }

	    /**
	     * 订单子表(关联名称项)
	     *
	     * 创建日期：(2001-6-23)
	     * @return nc.vo.sc.order.OrderItemVO
	     * @param key String
	     * @exception java.sql.SQLException 异常说明。
	     */
	    public OrderItemVO[] queryItemsByCondition(String condition) throws SQLException {

	        /*************************************************************/
	        // 保留的系统管理接口：
	        beforeCallMethod("nc.bs.sc.order.OrderDMOForCG", "queryItemsByCondition", new Object[] { condition });
	        /*************************************************************/
	        String patch = "";
	        patch += " left join sc_order on sc_order_b.corderid=sc_order.corderid ";
	        patch += " left join sc_order_ddlb on sc_order_ddlb.corderid=sc_order.corderid";
	        //加工品
	        patch += " left join bd_invbasdoc on sc_order_b.cbaseid=bd_invbasdoc.pk_invbasdoc  ";
	        //主计量单位
	        patch += " left join bd_measdoc measdo1 on bd_invbasdoc.pk_measdoc=measdo1.pk_measdoc    ";
	        //辅计量单位
	        patch += " left join bd_measdoc measdo2 on sc_order_b.cassistunit=measdo2.pk_measdoc   ";
	        //仓库
	        patch += " left join bd_stordoc on sc_order_b.cwarehouseid=bd_stordoc.pk_stordoc   ";
	        //项目
	        patch += " left join bd_jobmngfil on sc_order_b.cprojectid=bd_jobmngfil.pk_jobmngfil   ";
	        patch += " left join bd_jobbasfil on bd_jobbasfil.pk_jobbasfil=bd_jobmngfil.pk_jobbasfil   ";
	        //项目阶段
	        patch += " left join bd_jobobjpha on sc_order_b.cprojectphaseid=bd_jobobjpha.pk_jobobjpha   ";
	        patch += " left join bd_jobphase on bd_jobobjpha.pk_jobphase = bd_jobphase.pk_jobphase   ";
	        //币种
	        patch += " left join bd_currtype on sc_order_b.ccurrencytypeid = bd_currtype.pk_currtype  ";

	        //select table sql
	        String select = "   select distinct  sc_order_b.corder_bid, sc_order_b.corderid, sc_order_b.pk_corp, sc_order_b.cmangid, sc_order_b.cbaseid, sc_order_b.nordernum,  ";
	        select += " sc_order_b.cassistunit, sc_order_b.nassistnum, sc_order_b.ndiscountrate, sc_order_b.idiscounttaxtype, sc_order_b.ntaxrate,  ";
	        select += " sc_order_b.ccurrencytypeid, sc_order_b.noriginalnetprice, sc_order_b.noriginalcurprice, sc_order_b.noriginalcurmny,  ";
	        select += "  sc_order_b.noriginaltaxmny, sc_order_b.noriginalsummny, sc_order_b.nexchangeotobrate, sc_order_b.ntaxmny, sc_order_b.nmoney,  ";
	        select += " sc_order_b.nsummny,  ";
	        select += " sc_order_b.naccumarrvnum, sc_order_b.naccumstorenum, sc_order_b.naccuminvoicenum, sc_order_b.naccumwastnum,  ";
	        select += " sc_order_b.dplanarrvdate, sc_order_b.cwarehouseid, sc_order_b.creceiveaddress, sc_order_b.cprojectid,   ";
	        select += " sc_order_b.cprojectphaseid, sc_order_b.coperator, sc_order_b.forderrowstatus, sc_order_b.bisactive, sc_order_b.cordersource,  ";
	        select += " sc_order_b.csourcebillid, sc_order_b.csourcebillrow, sc_order_b.cupsourcebilltype, sc_order_b.cupsourcebillid,  ";
	        select += " sc_order_b.cupsourcebillrowid, sc_order_b.vmemo, sc_order_b.vfree1, sc_order_b.vfree2, sc_order_b.vfree3, sc_order_b.vfree4, sc_order_b.vfree5,  ";
	        select += " sc_order_b.vdef1, sc_order_b.vdef2, sc_order_b.vdef3, sc_order_b.vdef4, sc_order_b.vdef5, sc_order_b.vdef6, sc_order_b.vdef7, sc_order_b.vdef8, sc_order_b.vdef9, sc_order_b.vdef10" +
	            ", sc_order_b.vdef11, sc_order_b.vdef12, sc_order_b.vdef13, sc_order_b.vdef14, sc_order_b.vdef15, sc_order_b.vdef16, sc_order_b.vdef17, sc_order_b.vdef18, sc_order_b.vdef19, sc_order_b.vdef20" +
	            ", sc_order_b.pk_defdoc1, sc_order_b.pk_defdoc2, sc_order_b.pk_defdoc3, sc_order_b.pk_defdoc4, sc_order_b.pk_defdoc5, sc_order_b.pk_defdoc6, sc_order_b.pk_defdoc7" +
	            ", sc_order_b.pk_defdoc8, sc_order_b.pk_defdoc9, sc_order_b.pk_defdoc10, sc_order_b.pk_defdoc11, sc_order_b.pk_defdoc12, sc_order_b.pk_defdoc13, sc_order_b.pk_defdoc14" +
	            ", sc_order_b.pk_defdoc15, sc_order_b.pk_defdoc16, sc_order_b.pk_defdoc17, sc_order_b.pk_defdoc18, sc_order_b.pk_defdoc19, sc_order_b.pk_defdoc20" +
	            ", sc_order_b.crowno, sc_order_b.norgtaxprice, sc_order_b.norgnettaxprice, sc_order_b.vproducenum,sc_order_b.ccontractid,sc_order_b.ccontractrowid,sc_order_b.ccontractrcode" +
	            ",sc_order_b.vpriceauditcode,sc_order_b.cpriceauditid,sc_order_b.cpriceaudit_bid,sc_order_b.cpriceaudit_bb1id   ";

	        //select name
	        StringBuffer strbuf = new StringBuffer();
	        //加工品编码、名称、规格、型号
	        strbuf.append(" ,invcode,invname,invspec,invtype  ");
	        //单位
	        strbuf.append(" ,measdo1.measname  ");
	        //辅单位
	        strbuf.append(" ,measdo2.measname  ");
	        //仓库
	        strbuf.append(" ,bd_stordoc.storname  ");
	        //项目
	        strbuf.append(" ,bd_jobbasfil.jobname  ");
	        //项目阶段
	        strbuf.append(" ,bd_jobphase.jobphasename  ");
	        //币种
	        strbuf.append(" , bd_currtype.currtypename   ");
	        //ts
	        strbuf.append(" , sc_order_b.ts");
	        //
	        strbuf.append(" , sc_order_b.nbackarrvnum");
	        //
	        strbuf.append(" , sc_order_b.nbackstorenum, sc_order_b.csourcebillcode, sc_order_b.csourcebillrowno");

	        String sql = select + strbuf.toString() + " from sc_order_b " + patch + 
	        		" where sc_order_b.dr=0 "+condition+" order by sc_order_b.crowno";

	        OrderItemVO[] orderItems = null;
	        Vector v = new Vector();
	        Connection con = null;
	        PreparedStatement stmt = null;
	        try {
	            con = getConnection();
	            stmt = con.prepareStatement(sql);
	            ResultSet rs = stmt.executeQuery();
	            //
	            while (rs.next()) {
	                OrderItemVO orderItem = new OrderItemVO();
	                //
	                String corder_bid = rs.getString("corder_bid");
	                orderItem.setCorder_bid(corder_bid == null ? null : corder_bid.trim());
	                //
	                String corderid = rs.getString("corderid");
	                orderItem.setCorderid(corderid == null ? null : corderid.trim());
	                //
	                String pk_corp = rs.getString("pk_corp");
	                orderItem.setPk_corp(pk_corp == null ? null : pk_corp.trim());
	                //
	                String cmangid = rs.getString("cmangid");
	                orderItem.setCmangid(cmangid == null ? null : cmangid.trim());
	                //
	                String cbaseid = rs.getString("cbaseid");
	                orderItem.setCbaseid(cbaseid == null ? null : cbaseid.trim());
	                //
	                BigDecimal nordernum = rs.getBigDecimal("nordernum");
	                orderItem.setNordernum(nordernum == null ? null : new UFDouble(nordernum));
	                orderItem.setNoldnum(nordernum == null ? null : new UFDouble(nordernum));
	                //
	                String cassistunit = rs.getString("cassistunit");
	                orderItem.setCassistunit(cassistunit == null ? null : cassistunit.trim());
	                //
	                BigDecimal nassistnum = (BigDecimal)rs.getObject("nassistnum");
	                orderItem.setNassistnum(nassistnum == null ? null : new UFDouble(nassistnum));
	                //
	                BigDecimal ndiscountrate = (BigDecimal)rs.getObject("ndiscountrate");
	                orderItem.setNdiscountrate(ndiscountrate == null ? null : new UFDouble(ndiscountrate));
	                //
	                Integer idiscounttaxtype = (Integer) rs.getObject("idiscounttaxtype");
	                orderItem.setIdiscounttaxtype(idiscounttaxtype == null ? null : idiscounttaxtype);
	                //
	                BigDecimal ntaxrate = (BigDecimal)rs.getObject("ntaxrate");
	                orderItem.setNtaxrate(ntaxrate == null ? null : new UFDouble(ntaxrate));
	                //
	                String ccurrencytypeid = rs.getString("ccurrencytypeid");
	                orderItem.setCcurrencytypeid(ccurrencytypeid == null ? null : ccurrencytypeid.trim());
	                //
	                BigDecimal noriginalnetprice = (BigDecimal)rs.getObject("noriginalnetprice");
	                orderItem.setNoriginalnetprice(noriginalnetprice == null ? null : new UFDouble(noriginalnetprice));
	                //
	                BigDecimal noriginalcurprice = (BigDecimal)rs.getObject("noriginalcurprice");
	                orderItem.setNoriginalcurprice(noriginalcurprice == null ? null : new UFDouble(noriginalcurprice));
	                //
	                BigDecimal noriginalcurmny = (BigDecimal)rs.getObject("noriginalcurmny");
	                orderItem.setNoriginalcurmny(noriginalcurmny == null ? null : new UFDouble(noriginalcurmny));
	                //
	                BigDecimal noriginaltaxmny = (BigDecimal)rs.getObject("noriginaltaxmny");
	                orderItem.setNoriginaltaxmny(noriginaltaxmny == null ? null : new UFDouble(noriginaltaxmny));
	                //
	                BigDecimal noriginalsummny = (BigDecimal)rs.getObject("noriginalsummny");
	                orderItem.setNoriginalsummny(noriginalsummny == null ? null : new UFDouble(noriginalsummny));
	                //
	                BigDecimal nexchangeotobrate = (BigDecimal)rs.getObject("nexchangeotobrate");
	                orderItem.setNexchangeotobrate(nexchangeotobrate == null ? null : new UFDouble(nexchangeotobrate));
	                //
	                BigDecimal ntaxmny = (BigDecimal)rs.getObject("ntaxmny");
	                orderItem.setNtaxmny(ntaxmny == null ? null : new UFDouble(ntaxmny));
	                //
	                BigDecimal nmoney = (BigDecimal)rs.getObject("nmoney");
	                orderItem.setNmoney(nmoney == null ? null : new UFDouble(nmoney));
	                //
	                BigDecimal nsummny = (BigDecimal)rs.getObject("nsummny");
	                orderItem.setNsummny(nsummny == null ? null : new UFDouble(nsummny));
	                //
	                BigDecimal naccumarrvnum = (BigDecimal)rs.getObject("naccumarrvnum");
	                orderItem.setNaccumarrvnum(naccumarrvnum == null ? null : new UFDouble(naccumarrvnum));
	                //
	                BigDecimal naccumstorenum = (BigDecimal)rs.getObject("naccumstorenum");
	                orderItem.setNaccumstorenum(naccumstorenum == null ? null : new UFDouble(naccumstorenum));
	                //
	                BigDecimal naccuminvoicenum = (BigDecimal)rs.getObject("naccuminvoicenum");
	                orderItem.setNaccuminvoicenum(naccuminvoicenum == null ? null : new UFDouble(naccuminvoicenum));
	                //
	                BigDecimal naccumwastnum = (BigDecimal)rs.getObject("naccumwastnum");
	                orderItem.setNaccumwastnum(naccumwastnum == null ? null : new UFDouble(naccumwastnum));
	                //
	                String dplanarrvdate = rs.getString("dplanarrvdate");
	                orderItem.setDplanarrvdate(dplanarrvdate == null ? null : new UFDate(dplanarrvdate.trim(), false));
	                //
	                String cwarehouseid = rs.getString("cwarehouseid");
	                orderItem.setCwarehouseid(cwarehouseid == null ? null : cwarehouseid.trim());
	                //
	                String creceiveaddress = rs.getString("creceiveaddress");
	                orderItem.setCreceiveaddress(creceiveaddress == null ? null : creceiveaddress.trim());
	                //
	                String cprojectid = rs.getString("cprojectid");
	                orderItem.setCprojectid(cprojectid == null ? null : cprojectid.trim());
	                //
	                String cprojectphaseid = rs.getString("cprojectphaseid");
	                orderItem.setCprojectphaseid(cprojectphaseid == null ? null : cprojectphaseid.trim());
	                //
	                String coperator = rs.getString("coperator");
	                orderItem.setCoperator(coperator == null ? null : coperator.trim());
	                //
	                Integer forderrowstatus = (Integer) rs.getObject("forderrowstatus");
	                orderItem.setForderrowstatus(forderrowstatus == null ? null : forderrowstatus);
	                //
	                String bisactive = rs.getString("bisactive");
	                if (bisactive == null)
	                    orderItem.setBisactive(null);
	                else if (bisactive.trim().equals("1"))
	                    orderItem.setBisactive(new UFBoolean(false));
	                else
	                    orderItem.setBisactive(new UFBoolean(true));
	                //orderItem.setBisactive(bisactive == null ? null : new UFBoolean(bisactive.trim()));
	                //
	                String cordersource = rs.getString("cordersource");
	                orderItem.setCordersource(cordersource == null ? null : cordersource.trim());
	                //
	                String csourcebillid = rs.getString("csourcebillid");
	                orderItem.setCsourcebillid(csourcebillid == null ? null : csourcebillid.trim());
	                //
	                String csourcebillrow = rs.getString("csourcebillrow");
	                orderItem.setCsourcebillrow(csourcebillrow == null ? null : csourcebillrow.trim());
	                //
	                String cupsourcebilltype = rs.getString("cupsourcebilltype");
	                orderItem.setCupsourcebilltype(cupsourcebilltype == null ? null : cupsourcebilltype.trim());
	                //
	                String cupsourcebillid = rs.getString("cupsourcebillid");
	                orderItem.setCupsourcebillid(cupsourcebillid == null ? null : cupsourcebillid.trim());
	                //
	                String cupsourcebillrowid = rs.getString("cupsourcebillrowid");
	                orderItem.setCupsourcebillrowid(cupsourcebillrowid == null ? null : cupsourcebillrowid.trim());
	                //
	                String vmemo = rs.getString("vmemo");
	                orderItem.setVmemo(vmemo == null ? null : vmemo.trim());
	                //
	                String vfree1 = rs.getString("vfree1");
	                orderItem.setVfree1(vfree1 == null ? null : vfree1.trim());
	                //
	                String vfree2 = rs.getString("vfree2");
	                orderItem.setVfree2(vfree2 == null ? null : vfree2.trim());
	                //
	                String vfree3 = rs.getString("vfree3");
	                orderItem.setVfree3(vfree3 == null ? null : vfree3.trim());
	                //
	                String vfree4 = rs.getString("vfree4");
	                orderItem.setVfree4(vfree4 == null ? null : vfree4.trim());
	                //
	                String vfree5 = rs.getString("vfree5");
	                orderItem.setVfree5(vfree5 == null ? null : vfree5.trim());
	                //
	                String vdef1 = rs.getString("vdef1");
	                orderItem.setVdef1(vdef1 == null ? null : vdef1.trim());
	                //
	                String vdef2 = rs.getString("vdef2");
	                orderItem.setVdef2(vdef2 == null ? null : vdef2.trim());
	                //
	                String vdef3 = rs.getString("vdef3");
	                orderItem.setVdef3(vdef3 == null ? null : vdef3.trim());
	                //
	                String vdef4 = rs.getString("vdef4");
	                orderItem.setVdef4(vdef4 == null ? null : vdef4.trim());
	                //
	                String vdef5 = rs.getString("vdef5");
	                orderItem.setVdef5(vdef5 == null ? null : vdef5.trim());
	                //
	                String vdef6 = rs.getString("vdef6");
	                orderItem.setVdef6(vdef6 == null ? null : vdef6.trim());
	                //
	                String vdef7 = rs.getString("vdef7");
	                orderItem.setVdef7(vdef7 == null ? null : vdef7.trim());
	                //
	                String vdef8 = rs.getString("vdef8");
	                orderItem.setVdef8(vdef8 == null ? null : vdef8.trim());
	                //
	                String vdef9 = rs.getString("vdef9");
	                orderItem.setVdef9(vdef9 == null ? null : vdef9.trim());
	                //
	                String vdef10 = rs.getString("vdef10");
	                orderItem.setVdef10(vdef10 == null ? null : vdef10.trim());
	                //
	                String vdef11 = rs.getString("vdef11");
	                orderItem.setVdef11(vdef11 == null ? null : vdef11.trim());
	                //
	                String vdef12 = rs.getString("vdef12");
	                orderItem.setVdef12(vdef12 == null ? null : vdef12.trim());
	                //
	                String vdef13 = rs.getString("vdef13");
	                orderItem.setVdef13(vdef13 == null ? null : vdef13.trim());
	                //
	                String vdef14 = rs.getString("vdef14");
	                orderItem.setVdef14(vdef14 == null ? null : vdef14.trim());
	                //
	                String vdef15 = rs.getString("vdef15");
	                orderItem.setVdef15(vdef15 == null ? null : vdef15.trim());
	                //
	                String vdef16 = rs.getString("vdef16");
	                orderItem.setVdef16(vdef16 == null ? null : vdef16.trim());
	                //
	                String vdef17 = rs.getString("vdef17");
	                orderItem.setVdef17(vdef17 == null ? null : vdef17.trim());
	                //
	                String vdef18 = rs.getString("vdef18");
	                orderItem.setVdef18(vdef18 == null ? null : vdef18.trim());
	                //
	                String vdef19 = rs.getString("vdef19");
	                orderItem.setVdef19(vdef19 == null ? null : vdef19.trim());
	                //
	                String vdef20 = rs.getString("vdef20");
	                orderItem.setVdef20(vdef20 == null ? null : vdef20.trim());
	                //
	                String pk_defdoc1 = rs.getString("pk_defdoc1");
	                orderItem.setPKDefDoc1(pk_defdoc1 == null ? null : pk_defdoc1.trim());
	                //
	                String pk_defdoc2 = rs.getString("pk_defdoc2");
	                orderItem.setPKDefDoc2(pk_defdoc2 == null ? null : pk_defdoc2.trim());
	                //
	                String pk_defdoc3 = rs.getString("pk_defdoc3");
	                orderItem.setPKDefDoc3(pk_defdoc3 == null ? null : pk_defdoc3.trim());
	                //
	                String pk_defdoc4 = rs.getString("pk_defdoc4");
	                orderItem.setPKDefDoc4(pk_defdoc4 == null ? null : pk_defdoc4.trim());
	                //
	                String pk_defdoc5 = rs.getString("pk_defdoc5");
	                orderItem.setPKDefDoc5(pk_defdoc5 == null ? null : pk_defdoc5.trim());
	                //
	                String pk_defdoc6 = rs.getString("pk_defdoc6");
	                orderItem.setPKDefDoc6(pk_defdoc6 == null ? null : pk_defdoc6.trim());
	                //
	                String pk_defdoc7 = rs.getString("pk_defdoc7");
	                orderItem.setPKDefDoc7(pk_defdoc7 == null ? null : pk_defdoc7.trim());
	                //
	                String pk_defdoc8 = rs.getString("pk_defdoc8");
	                orderItem.setPKDefDoc8(pk_defdoc8 == null ? null : pk_defdoc8.trim());
	                //
	                String pk_defdoc9 = rs.getString("pk_defdoc9");
	                orderItem.setPKDefDoc9(pk_defdoc9 == null ? null : pk_defdoc9.trim());
	                //
	                String pk_defdoc10 = rs.getString("pk_defdoc10");
	                orderItem.setPKDefDoc10(pk_defdoc10 == null ? null : pk_defdoc10.trim());
	                //
	                String pk_defdoc11 = rs.getString("pk_defdoc11");
	                orderItem.setPKDefDoc11(pk_defdoc11 == null ? null : pk_defdoc11.trim());
	                //
	                String pk_defdoc12 = rs.getString("pk_defdoc12");
	                orderItem.setPKDefDoc12(pk_defdoc12 == null ? null : pk_defdoc12.trim());
	                //
	                String pk_defdoc13 = rs.getString("pk_defdoc13");
	                orderItem.setPKDefDoc13(pk_defdoc13 == null ? null : pk_defdoc13.trim());
	                //
	                String pk_defdoc14 = rs.getString("pk_defdoc14");
	                orderItem.setPKDefDoc14(pk_defdoc14 == null ? null : pk_defdoc14.trim());
	                //
	                String pk_defdoc15 = rs.getString("pk_defdoc15");
	                orderItem.setPKDefDoc15(pk_defdoc15 == null ? null : pk_defdoc15.trim());
	                //
	                String pk_defdoc16 = rs.getString("pk_defdoc16");
	                orderItem.setPKDefDoc16(pk_defdoc16 == null ? null : pk_defdoc16.trim());
	                //
	                String pk_defdoc17 = rs.getString("pk_defdoc17");
	                orderItem.setPKDefDoc17(pk_defdoc17 == null ? null : pk_defdoc17.trim());
	                //
	                String pk_defdoc18 = rs.getString("pk_defdoc18");
	                orderItem.setPKDefDoc18(pk_defdoc18 == null ? null : pk_defdoc18.trim());
	                //
	                String pk_defdoc19 = rs.getString("pk_defdoc19");
	                orderItem.setPKDefDoc19(pk_defdoc19 == null ? null : pk_defdoc19.trim());
	                //
	                String pk_defdoc20 = rs.getString("pk_defdoc20");
	                orderItem.setPKDefDoc20(pk_defdoc20 == null ? null : pk_defdoc20.trim());
	                //
	                String crowno = rs.getString("crowno");
	                orderItem.setCrowno(crowno == null ? null : crowno.trim());
	                //
	                BigDecimal norgtaxprice = (BigDecimal)rs.getObject("norgtaxprice");
	                orderItem.setNorgtaxprice(norgtaxprice == null ? null : new UFDouble(norgtaxprice));
	                //
	                BigDecimal norgnettaxprice = (BigDecimal)rs.getObject("norgnettaxprice");
	                orderItem.setNorgnettaxprice(norgnettaxprice == null ? null : new UFDouble(norgnettaxprice));
	                //
	                //vproducenum：
	                String vproducenum = rs.getString("vproducenum");
	                orderItem.setVproducenum(vproducenum == null ? null : vproducenum.trim());

	                //
	                String ccontractid = rs.getString("ccontractid");
	                orderItem.setCcontractid(ccontractid == null ? null : ccontractid.trim());
	                //
	                //
	                String ccontractrowid = rs.getString("ccontractrowid");
	                orderItem.setCcontractrowid(ccontractrowid == null ? null : ccontractrowid.trim());
	                //
	                //
	                String ccontractrcode = rs.getString("ccontractrcode");
	                orderItem.setCcontractrcode(ccontractrcode == null ? null : ccontractrcode.trim());
	                //
	                
	                String vpriceauditcode = rs.getString("vpriceauditcode");
	                orderItem.setVpriceauditcode(vpriceauditcode == null ? null : vpriceauditcode.trim());
	                
	                String cpriceauditid = rs.getString("cpriceauditid");
	                orderItem.setCpriceauditid(cpriceauditid == null ? null : cpriceauditid.trim());
	                
	                String cpriceaudit_bid = rs.getString("cpriceaudit_bid");
	                orderItem.setCpriceaudit_bid(cpriceaudit_bid == null ? null : cpriceaudit_bid.trim());
	                
	                String cpriceaudit_bb1id = rs.getString("cpriceaudit_bb1id");
	                orderItem.setCpriceaudit_bb1id(cpriceaudit_bb1id == null ? null : cpriceaudit_bb1id.trim());

	                //add name
	                String invcode = rs.getString("invcode");
	                orderItem.setVinvcode(invcode == null ? null : invcode.trim());
	                //
	                String invname = rs.getString("invname");
	                orderItem.setVinvname(invname == null ? null : invname.trim());
	                //
	                String invspec = rs.getString("invspec");
	                orderItem.setVinvspec(invspec == null ? null : invspec.trim());
	                //
	                String invtype = rs.getString("invtype");
	                orderItem.setVinvtype(invtype == null ? null : invtype.trim());
	                //
	                int index = 101;
	                String measdocname = rs.getString(index++);
	                orderItem.setVmeasdocname(measdocname == null ? null : measdocname.trim());
	                //
	                String assunitname = rs.getString(index++);
	                orderItem.setVassunitname(assunitname == null ? null : assunitname.trim());
	                //
	                String storename = rs.getString(index++);
	                orderItem.setVwarehousename(storename == null ? null : storename.trim());
	                //
	                String projectname = rs.getString(index++);
	                orderItem.setVprojectname(projectname == null ? null : projectname.trim());
	                //
	                String projectphasename = rs.getString(index++);
	                orderItem.setVprojectphasename(projectphasename == null ? null : projectphasename.trim());
	                //
	                String currencyname = rs.getString(index++);
	                orderItem.setVcurrencyname(currencyname == null ? null : currencyname.trim());
	                //
	                String ts = rs.getString(index++);
	                orderItem.setTs(ts == null ? null : ts.trim());
	                //nbackarrvnum
	                BigDecimal nbackarrvnum = (BigDecimal)rs.getObject(index++);
	                orderItem.setNbackarrvnum(nbackarrvnum == null ? null : new UFDouble(nbackarrvnum));
	                //nbackstorenum
	                BigDecimal nbackstorenum = (BigDecimal)rs.getObject(index++);
	                orderItem.setNbackstorenum(nbackstorenum == null ? null : new UFDouble(nbackstorenum));
	                String csourcebillcode = rs.getString("csourcebillcode");
	                orderItem.setCsourcebillcode(csourcebillcode == null ? null : csourcebillcode.trim());
	                String csourcebillrowno = rs.getString("csourcebillrowno");
	                orderItem.setCsourcebillrowno(csourcebillrowno == null ? null : csourcebillrowno.trim());

	                v.addElement(orderItem);
	            }
	        } finally {
	            try {
	                if (stmt != null) {
	                    stmt.close();
	                }
	            } catch (Exception e) {
	            }
	            try {
	                if (con != null) {
	                    con.close();
	                }
	            } catch (Exception e) {
	            }
	        }
	        orderItems = new OrderItemVO[v.size()];
	        if (v.size() > 0) {
	            v.copyInto(orderItems);
	        }

	        /*************************************************************/
	        // 保留的系统管理接口：
	        afterCallMethod("nc.bs.sc.order.OrderDMO", "findItemsAllForHeader", new Object[] { condition });
	        /*************************************************************/

	        return orderItems;
	    }

	    /**
	     * 此处插入方法说明。
	     * 创建日期：(01-6-21 9:34:41)
	     * @return nc.vo.sc.order.OrderItemVO[]
	     * @param item nc.vo.sc.order.OrderItemVO[]
	     */
	    public OrderItemVO[] getUnionItem(OrderItemVO[] item) throws SQLException {

	        Vector v = new Vector();
	        for (int i = 0; i < item.length; i++) {
	            item[i].setCinvshow(ScConstants.PROCESSFLAG);

	            v.addElement(item[i]);
	        }
	        OrderItemVO[] unionItem = new OrderItemVO[v.size()];
	        if (v.size() > 0) {
	            v.copyInto(unionItem);
	        }
	        return unionItem;

	    }

	public OrderVO[] queryBillVO(String condition) throws SQLException, BusinessException {
		// TODO Auto-generated method stub
		OrderHeaderVO[] headvos = queryHeadByCondition(condition);
		if(headvos == null || headvos.length <=0)
			return null;
		OrderItemVO[] item = queryItemsByCondition(condition);
		IUAPQueryBS bo = NCLocator.getInstance().lookup(IUAPQueryBS.class);
		String sql = "select distinct sc_order_ddlb.* from sc_order " +
				"left join sc_order_b on sc_order_b.corderid=sc_order.corderid "+
				" left join sc_order_ddlb on sc_order_ddlb.corderid=sc_order.corderid"+
				" where isnull(sc_order.dr,0)=0 and isnull(sc_order_b.dr,0)=0 and isnull(sc_order_ddlb.dr,0)=0 ";
		ArrayList<OrderDdlbVO> list = (ArrayList<OrderDdlbVO>) bo.executeQuery(sql, new BeanListProcessor(OrderDdlbVO.class));
		
		//组合
		OrderVO[] billvo = new OrderVO[headvos.length];
		for (int i = 0; i < billvo.length; i++) {
			billvo[i] = new OrderVO();
			billvo[i].setParentVO(headvos[i]);
			String headid = headvos[i].getPrimaryKey();
			ArrayList<OrderDdlbVO> list_d = new ArrayList<OrderDdlbVO>(); 
			for (int j = 0; list !=null && list.size() > 0 && j < list.size(); j++) {
				OrderDdlbVO ddlb = list.get(j);
				if(ddlb != null && ddlb.getCorderid() != null &&ddlb.getCorderid().equals(headid))
					list_d.add(ddlb);
			}
			ArrayList<OrderItemVO> list_b = new ArrayList<OrderItemVO>(); 
			for (int j = 0; item !=null && item.length > 0 && j < item.length; j++) {
				if(item[j].getCorderid().equals(headid))
					list_b.add(item[j]);
			}
			billvo[i].setChildrenVO(list_b.toArray(new OrderItemVO[0]));
			billvo[i].setDdlbvos(list_d.toArray(new OrderDdlbVO[0]));
		}
		return billvo;
    }

	private OrderHeaderVO[] queryHeadByCondition(String condition)
			throws SQLException {
		String sql = "select distinct sc_order.corderid, sc_order.vordercode, sc_order.pk_corp, sc_order.cpurorganization, sc_order.cwareid," +
				" sc_order.dorderdate, sc_order.cvendorid, sc_order.caccountbankid, sc_order.cdeptid, sc_order.cemployeeid, " +
				" sc_order.cbiztype, sc_order.creciever, sc_order.cgiveinvoicevendor, sc_order.ctransmodeid, sc_order.ctermProtocolid," +
				" sc_order.ibillstatus, sc_order.vmemo, sc_order.caccountyear, sc_order.coperator, sc_order.vdef1, sc_order.vdef2, " +
				" sc_order.vdef3, sc_order.vdef4, sc_order.vdef5, sc_order.vdef6, sc_order.vdef7, sc_order.vdef8, sc_order.vdef9, " +
				" sc_order.vdef10, sc_order.vdef11, sc_order.vdef12, sc_order.vdef13, sc_order.vdef14, sc_order.vdef15, sc_order.vdef16," +
				" sc_order.vdef17, sc_order.vdef18, sc_order.vdef19, sc_order.vdef20, sc_order.pk_defdoc1, sc_order.pk_defdoc2, " +
				" sc_order.pk_defdoc3, sc_order.pk_defdoc4, sc_order.pk_defdoc5, sc_order.pk_defdoc6, sc_order.pk_defdoc7, sc_order.pk_defdoc8," +
				" sc_order.pk_defdoc9, sc_order.pk_defdoc10, sc_order.pk_defdoc11, sc_order.pk_defdoc12, sc_order.pk_defdoc13, " +
				" sc_order.pk_defdoc14, sc_order.pk_defdoc15, sc_order.pk_defdoc16, sc_order.pk_defdoc17, sc_order.pk_defdoc18, " +
				" sc_order.pk_defdoc19, sc_order.pk_defdoc20, sc_order.ts, sc_order.iprintcount, sc_order.tmaketime, sc_order.taudittime, sc_order.tlastmaketime  " +
				"from sc_order " +
				" left join sc_order_b on sc_order_b.corderid=sc_order.corderid "+
				" left join sc_order_ddlb on sc_order_ddlb.corderid=sc_order.corderid"+
				" where isnull(sc_order.dr,0)=0 and isnull(sc_order_b.dr,0)=0 and isnull(sc_order_ddlb.dr,0)=0 "+
				condition;
		
		OrderHeaderVO orders[] = null;
        Vector v = new Vector();
        Connection con = null;
        PreparedStatement stmt = null;
        try {
        	 con = getConnection();
             stmt = con.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery();
            //
            while (rs.next()) {
                OrderHeaderVO order = new OrderHeaderVO();
                // corderid :
                String corderid = rs.getString(1);
                order.setCorderid(corderid == null ? null : corderid.trim());
                // vordercode :
                String vordercode = rs.getString(2);
                order.setVordercode(vordercode == null ? null : vordercode.trim());
                // pk_corp :
                String pk_corp = rs.getString(3);
                order.setPk_corp(pk_corp == null ? null : pk_corp.trim());
                // cpurorganization :
                String cpurorganization = rs.getString(4);
                order.setCpurorganization(cpurorganization == null ? null : cpurorganization.trim());
                // cwareid :
                String cwareid = rs.getString(5);
                order.setCwareid(cwareid == null ? null : cwareid.trim());
                // dorderdate :
                String dorderdate = rs.getString(6);
                order.setDorderdate(dorderdate == null ? null : new UFDate(dorderdate.trim(), false));
                // cvendorid :
                String cvendorid = rs.getString(7);
                order.setCvendorid(cvendorid == null ? null : cvendorid.trim());
                // caccountbankid :
                String caccountbankid = rs.getString(8);
                order.setCaccountbankid(caccountbankid == null ? null : caccountbankid.trim());
                // cdeptid :
                String cdeptid = rs.getString(9);
                order.setCdeptid(cdeptid == null ? null : cdeptid.trim());
                // cemployeeid :
                String cemployeeid = rs.getString(10);
                order.setCemployeeid(cemployeeid == null ? null : cemployeeid.trim());
                // cbiztypeid :
                String cbiztypeid = rs.getString(11);
                order.setCbiztype(cbiztypeid == null ? null : cbiztypeid.trim());
                // creciever :
                String creciever = rs.getString(12);
                order.setCreciever(creciever == null ? null : creciever.trim());
                // cgiveinvoicevendor :
                String cgiveinvoicevendor = rs.getString(13);
                order.setCgiveinvoicevendor(cgiveinvoicevendor == null ? null : cgiveinvoicevendor.trim());
                // ctransmodeid :
                String ctransmodeid = rs.getString(14);
                order.setCtransmodeid(ctransmodeid == null ? null : ctransmodeid.trim());
                // ctermProtocolid :
                String ctermProtocolid = rs.getString(15);
                order.setCtermProtocolid(ctermProtocolid == null ? null : ctermProtocolid.trim());
                // ibillstatus :
                Integer ibillstatus = (Integer) rs.getObject(16);
                order.setIbillstatus(ibillstatus == null ? null : ibillstatus);
                // vmemo :
                String vmemo = rs.getString(17);
                order.setVmemo(vmemo == null ? null : vmemo.trim());
                // caccountyear :
                String caccountyear = rs.getString(18);
                order.setCaccountyear(caccountyear == null ? null : caccountyear.trim());
                // coperator :
                String coperator = rs.getString(19);
                order.setCoperator(coperator == null ? null : coperator.trim());
                // vdef1 :
                String vdef1 = rs.getString(20);
                order.setVdef1(vdef1 == null ? null : vdef1.trim());
                // vdef2 :
                String vdef2 = rs.getString(21);
                order.setVdef2(vdef2 == null ? null : vdef2.trim());
                // vdef3 :
                String vdef3 = rs.getString(22);
                order.setVdef3(vdef3 == null ? null : vdef3.trim());
                // vdef4 :
                String vdef4 = rs.getString(23);
                order.setVdef4(vdef4 == null ? null : vdef4.trim());
                // vdef5 :
                String vdef5 = rs.getString(24);
                order.setVdef5(vdef5 == null ? null : vdef5.trim());
                // vdef6 :
                String vdef6 = rs.getString(25);
                order.setVdef6(vdef6 == null ? null : vdef6.trim());
                // vdef7 :
                String vdef7 = rs.getString(26);
                order.setVdef7(vdef7 == null ? null : vdef7.trim());
                // vdef8 :
                String vdef8 = rs.getString(27);
                order.setVdef8(vdef8 == null ? null : vdef8.trim());
                // vdef9 :
                String vdef9 = rs.getString(28);
                order.setVdef9(vdef9 == null ? null : vdef9.trim());
                // vdef10 :
                String vdef10 = rs.getString(29);
                order.setVdef10(vdef10 == null ? null : vdef10.trim());
                //
                //
                String vdef11 = rs.getString(30);
                order.setVdef11(vdef11 == null ? null : vdef11.trim());
                //
                String vdef12 = rs.getString(31);
                order.setVdef12(vdef12 == null ? null : vdef12.trim());
                //
                String vdef13 = rs.getString(32);
                order.setVdef13(vdef13 == null ? null : vdef13.trim());
                //
                String vdef14 = rs.getString(33);
                order.setVdef14(vdef14 == null ? null : vdef14.trim());
                //
                String vdef15 = rs.getString(34);
                order.setVdef15(vdef15 == null ? null : vdef15.trim());
                //
                String vdef16 = rs.getString(35);
                order.setVdef16(vdef16 == null ? null : vdef16.trim());
                //
                String vdef17 = rs.getString(36);
                order.setVdef17(vdef17 == null ? null : vdef17.trim());
                //
                String vdef18 = rs.getString(37);
                order.setVdef18(vdef18 == null ? null : vdef18.trim());
                //
                String vdef19 = rs.getString(38);
                order.setVdef19(vdef19 == null ? null : vdef19.trim());
                //
                String vdef20 = rs.getString(39);
                order.setVdef20(vdef20 == null ? null : vdef20.trim());
                //
                String pk_defdoc1 = rs.getString(40);
                order.setPKDefDoc1(pk_defdoc1 == null ? null : pk_defdoc1.trim());
                //
                String pk_defdoc2 = rs.getString(41);
                order.setPKDefDoc2(pk_defdoc2 == null ? null : pk_defdoc2.trim());
                //
                String pk_defdoc3 = rs.getString(42);
                order.setPKDefDoc3(pk_defdoc3 == null ? null : pk_defdoc3.trim());
                //
                String pk_defdoc4 = rs.getString(43);
                order.setPKDefDoc4(pk_defdoc4 == null ? null : pk_defdoc4.trim());
                //
                String pk_defdoc5 = rs.getString(44);
                order.setPKDefDoc5(pk_defdoc5 == null ? null : pk_defdoc5.trim());
                //
                String pk_defdoc6 = rs.getString(45);
                order.setPKDefDoc6(pk_defdoc6 == null ? null : pk_defdoc6.trim());
                //
                String pk_defdoc7 = rs.getString(46);
                order.setPKDefDoc7(pk_defdoc7 == null ? null : pk_defdoc7.trim());
                //
                String pk_defdoc8 = rs.getString(47);
                order.setPKDefDoc8(pk_defdoc8 == null ? null : pk_defdoc8.trim());
                //
                String pk_defdoc9 = rs.getString(48);
                order.setPKDefDoc9(pk_defdoc9 == null ? null : pk_defdoc9.trim());
                //
                String pk_defdoc10 = rs.getString(49);
                order.setPKDefDoc10(pk_defdoc10 == null ? null : pk_defdoc10.trim());
                //
                String pk_defdoc11 = rs.getString(50);
                order.setPKDefDoc11(pk_defdoc11 == null ? null : pk_defdoc11.trim());
                //
                String pk_defdoc12 = rs.getString(51);
                order.setPKDefDoc12(pk_defdoc12 == null ? null : pk_defdoc12.trim());
                //
                String pk_defdoc13 = rs.getString(52);
                order.setPKDefDoc13(pk_defdoc13 == null ? null : pk_defdoc13.trim());
                //
                String pk_defdoc14 = rs.getString(53);
                order.setPKDefDoc14(pk_defdoc14 == null ? null : pk_defdoc14.trim());
                //
                String pk_defdoc15 = rs.getString(54);
                order.setPKDefDoc15(pk_defdoc15 == null ? null : pk_defdoc15.trim());
                //
                String pk_defdoc16 = rs.getString(55);
                order.setPKDefDoc16(pk_defdoc16 == null ? null : pk_defdoc16.trim());
                //
                String pk_defdoc17 = rs.getString(56);
                order.setPKDefDoc17(pk_defdoc17 == null ? null : pk_defdoc17.trim());
                //
                String pk_defdoc18 = rs.getString(57);
                order.setPKDefDoc18(pk_defdoc18 == null ? null : pk_defdoc18.trim());
                //
                String pk_defdoc19 = rs.getString(58);
                order.setPKDefDoc19(pk_defdoc19 == null ? null : pk_defdoc19.trim());
                //
                String pk_defdoc20 = rs.getString(59);
                order.setPKDefDoc20(pk_defdoc20 == null ? null : pk_defdoc20.trim());
                // ts :
                String ts = rs.getString(60);
                order.setTs(ts == null ? null : ts.trim());
                // iprintcount :
                Integer iprintcount = (Integer) rs.getObject(61);
                order.setIprintcount(iprintcount == null ? null : iprintcount);

                String tmaketime = rs.getString(62);
                order.setTmaketime(tmaketime == null ? null : tmaketime.trim());
                String taudittime = rs.getString(63);
                order.setTaudittime(taudittime == null ? null : taudittime.trim());
                String tlastmaketime = rs.getString(64);
                order.setTlastmaketime(tlastmaketime == null ? null : tlastmaketime.trim());

                v.addElement(order);
            }
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
            } catch (Exception e) {
            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
            }
        }
        orders = new OrderHeaderVO[v.size()];
        if (v.size() > 0) {
            v.copyInto(orders);
        }

        /*************************************************************/
        // 保留的系统管理接口：
        afterCallMethod("nc.bs.sc.order.OrderDMO", "queryAllHead", new Object[] {condition });
        /*************************************************************/
		return orders;
	}

}