/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ztwzj.sapitf.voucher;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class VoucherQryInfo extends SuperVO {
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String vbusitype;
	private java.lang.String vbillcode;
	private nc.vo.pub.lang.UFDate ddate;
	private java.lang.String vbank;
	private java.lang.String vbkaccount;
	private java.lang.String pk_opporg;
	private java.lang.String voppbank;
	private java.lang.String voppbkacc;
	private nc.vo.pub.lang.UFDouble nmny;
	private java.lang.String udef1;
	private java.lang.String udef2;
	private java.lang.String udef3;
	private java.lang.String udef4;
	private java.lang.String udef5;
	private java.lang.String udef6;
	private java.lang.String udef7;
	private java.lang.String udef8;
	private java.lang.String udef9;
	private java.lang.String udef10;
	private java.lang.String pk_busibill;
	private nc.vo.pub.lang.UFBoolean bselect;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String VBUSITYPE = "vbusitype";
	public static final String VBILLCODE = "vbillcode";
	public static final String DDATE = "ddate";
	public static final String VBANK = "vbank";
	public static final String VBKACCOUNT = "vbkaccount";
	public static final String PK_OPPORG = "pk_opporg";
	public static final String VOPPBANK = "voppbank";
	public static final String VOPPBKACC = "voppbkacc";
	public static final String NMNY = "nmny";
	public static final String UDEF1 = "udef1";
	public static final String UDEF2 = "udef2";
	public static final String UDEF3 = "udef3";
	public static final String UDEF4 = "udef4";
	public static final String UDEF5 = "udef5";
	public static final String UDEF6 = "udef6";
	public static final String UDEF7 = "udef7";
	public static final String UDEF8 = "udef8";
	public static final String UDEF9 = "udef9";
	public static final String UDEF10 = "udef10";
	public static final String PK_BUSIBILL = "pk_busibill";
	public static final String BSELECT = "bselect";
			
	/**
	 * 属性pk_group的Getter方法.属性名：集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：公司
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：公司
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性vbusitype的Getter方法.属性名：业务类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbusitype () {
		return vbusitype;
	}   
	/**
	 * 属性vbusitype的Setter方法.属性名：业务类型
	 * 创建日期:
	 * @param newVbusitype java.lang.String
	 */
	public void setVbusitype (java.lang.String newVbusitype ) {
	 	this.vbusitype = newVbusitype;
	} 	  
	/**
	 * 属性vbillcode的Getter方法.属性名：单据号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbillcode () {
		return vbillcode;
	}   
	/**
	 * 属性vbillcode的Setter方法.属性名：单据号
	 * 创建日期:
	 * @param newVbillcode java.lang.String
	 */
	public void setVbillcode (java.lang.String newVbillcode ) {
	 	this.vbillcode = newVbillcode;
	} 	  
	/**
	 * 属性ddate的Getter方法.属性名：日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDdate () {
		return ddate;
	}   
	/**
	 * 属性ddate的Setter方法.属性名：日期
	 * 创建日期:
	 * @param newDdate nc.vo.pub.lang.UFDate
	 */
	public void setDdate (nc.vo.pub.lang.UFDate newDdate ) {
	 	this.ddate = newDdate;
	} 	  
	/**
	 * 属性vbank的Getter方法.属性名：开户行
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbank () {
		return vbank;
	}   
	/**
	 * 属性vbank的Setter方法.属性名：开户行
	 * 创建日期:
	 * @param newVbank java.lang.String
	 */
	public void setVbank (java.lang.String newVbank ) {
	 	this.vbank = newVbank;
	} 	  
	/**
	 * 属性vbkaccount的Getter方法.属性名：帐号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbkaccount () {
		return vbkaccount;
	}   
	/**
	 * 属性vbkaccount的Setter方法.属性名：帐号
	 * 创建日期:
	 * @param newVbkaccount java.lang.String
	 */
	public void setVbkaccount (java.lang.String newVbkaccount ) {
	 	this.vbkaccount = newVbkaccount;
	} 	  
	/**
	 * 属性pk_opporg的Getter方法.属性名：收(付)款单位PK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_opporg () {
		return pk_opporg;
	}   
	/**
	 * 属性pk_opporg的Setter方法.属性名：收(付)款单位PK
	 * 创建日期:
	 * @param newPk_opporg java.lang.String
	 */
	public void setPk_opporg (java.lang.String newPk_opporg ) {
	 	this.pk_opporg = newPk_opporg;
	} 	  
	/**
	 * 属性voppbank的Getter方法.属性名：收(付)款单位银行
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVoppbank () {
		return voppbank;
	}   
	/**
	 * 属性voppbank的Setter方法.属性名：收(付)款单位银行
	 * 创建日期:
	 * @param newVoppbank java.lang.String
	 */
	public void setVoppbank (java.lang.String newVoppbank ) {
	 	this.voppbank = newVoppbank;
	} 	  
	/**
	 * 属性voppbkacc的Getter方法.属性名：收(付)款单位账号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVoppbkacc () {
		return voppbkacc;
	}   
	/**
	 * 属性voppbkacc的Setter方法.属性名：收(付)款单位账号
	 * 创建日期:
	 * @param newVoppbkacc java.lang.String
	 */
	public void setVoppbkacc (java.lang.String newVoppbkacc ) {
	 	this.voppbkacc = newVoppbkacc;
	} 	  
	/**
	 * 属性nmny的Getter方法.属性名：金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getNmny () {
		return nmny;
	}   
	/**
	 * 属性nmny的Setter方法.属性名：金额
	 * 创建日期:
	 * @param newNmny nc.vo.pub.lang.UFDouble
	 */
	public void setNmny (nc.vo.pub.lang.UFDouble newNmny ) {
	 	this.nmny = newNmny;
	} 	  
	/**
	 * 属性udef1的Getter方法.属性名：自定义1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef1 () {
		return udef1;
	}   
	/**
	 * 属性udef1的Setter方法.属性名：自定义1
	 * 创建日期:
	 * @param newUdef1 java.lang.String
	 */
	public void setUdef1 (java.lang.String newUdef1 ) {
	 	this.udef1 = newUdef1;
	} 	  
	/**
	 * 属性udef2的Getter方法.属性名：自定义2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef2 () {
		return udef2;
	}   
	/**
	 * 属性udef2的Setter方法.属性名：自定义2
	 * 创建日期:
	 * @param newUdef2 java.lang.String
	 */
	public void setUdef2 (java.lang.String newUdef2 ) {
	 	this.udef2 = newUdef2;
	} 	  
	/**
	 * 属性udef3的Getter方法.属性名：自定义3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef3 () {
		return udef3;
	}   
	/**
	 * 属性udef3的Setter方法.属性名：自定义3
	 * 创建日期:
	 * @param newUdef3 java.lang.String
	 */
	public void setUdef3 (java.lang.String newUdef3 ) {
	 	this.udef3 = newUdef3;
	} 	  
	/**
	 * 属性udef4的Getter方法.属性名：自定义4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef4 () {
		return udef4;
	}   
	/**
	 * 属性udef4的Setter方法.属性名：自定义4
	 * 创建日期:
	 * @param newUdef4 java.lang.String
	 */
	public void setUdef4 (java.lang.String newUdef4 ) {
	 	this.udef4 = newUdef4;
	} 	  
	/**
	 * 属性udef5的Getter方法.属性名：自定义5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef5 () {
		return udef5;
	}   
	/**
	 * 属性udef5的Setter方法.属性名：自定义5
	 * 创建日期:
	 * @param newUdef5 java.lang.String
	 */
	public void setUdef5 (java.lang.String newUdef5 ) {
	 	this.udef5 = newUdef5;
	} 	  
	/**
	 * 属性udef6的Getter方法.属性名：自定义6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef6 () {
		return udef6;
	}   
	/**
	 * 属性udef6的Setter方法.属性名：自定义6
	 * 创建日期:
	 * @param newUdef6 java.lang.String
	 */
	public void setUdef6 (java.lang.String newUdef6 ) {
	 	this.udef6 = newUdef6;
	} 	  
	/**
	 * 属性udef7的Getter方法.属性名：自定义7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef7 () {
		return udef7;
	}   
	/**
	 * 属性udef7的Setter方法.属性名：自定义7
	 * 创建日期:
	 * @param newUdef7 java.lang.String
	 */
	public void setUdef7 (java.lang.String newUdef7 ) {
	 	this.udef7 = newUdef7;
	} 	  
	/**
	 * 属性udef8的Getter方法.属性名：自定义8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef8 () {
		return udef8;
	}   
	/**
	 * 属性udef8的Setter方法.属性名：自定义8
	 * 创建日期:
	 * @param newUdef8 java.lang.String
	 */
	public void setUdef8 (java.lang.String newUdef8 ) {
	 	this.udef8 = newUdef8;
	} 	  
	/**
	 * 属性udef9的Getter方法.属性名：自定义9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef9 () {
		return udef9;
	}   
	/**
	 * 属性udef9的Setter方法.属性名：自定义9
	 * 创建日期:
	 * @param newUdef9 java.lang.String
	 */
	public void setUdef9 (java.lang.String newUdef9 ) {
	 	this.udef9 = newUdef9;
	} 	  
	/**
	 * 属性udef10的Getter方法.属性名：自定义10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUdef10 () {
		return udef10;
	}   
	/**
	 * 属性udef10的Setter方法.属性名：自定义10
	 * 创建日期:
	 * @param newUdef10 java.lang.String
	 */
	public void setUdef10 (java.lang.String newUdef10 ) {
	 	this.udef10 = newUdef10;
	} 	  
	/**
	 * 属性pk_busibill的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_busibill () {
		return pk_busibill;
	}   
	/**
	 * 属性pk_busibill的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_busibill java.lang.String
	 */
	public void setPk_busibill (java.lang.String newPk_busibill ) {
	 	this.pk_busibill = newPk_busibill;
	} 	  
	/**
	 * 属性bselect的Getter方法.属性名：选择
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBselect () {
		return bselect;
	}   
	/**
	 * 属性bselect的Setter方法.属性名：选择
	 * 创建日期:
	 * @param newBselect nc.vo.pub.lang.UFBoolean
	 */
	public void setBselect (nc.vo.pub.lang.UFBoolean newBselect ) {
	 	this.bselect = newBselect;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_busibill";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cmp_ztw_voucheriftinfo";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cmp_ztw_voucheriftinfo";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public VoucherQryInfo() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.ztwzj.sapitf.voucher.VoucherQryInfo" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


